version: "3.9"

services:
  database:
    image: postgres
    container_name: codes_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=CodesApiDatabase
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: codes_api
    ports:
      - 44303:44303
    links:
      - database
    depends_on:
      - database
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local